### PR TITLE
Documentation Coverage Pipeline

### PR DESCRIPTION
**Pull request by alessandropellegrini**
This is a first attempt at providing information to the developers about
the quality of the documentation.

Signed-off-by: Alessandro Pellegrini <pellegrini@dis.uniroma1.it>

### CODE REVIEW

**Comment by alessandropellegrini** [comment]
Documentation coverage is 27.3% :exclamation:\[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.\n\n```\nDefines : 15.8% (74/469) Enum Values: 7.5% (63/835) Enums : 25.7% (9/35) Files : 77.1% (81/105) Functions : 40.3% (340/844) Pages : 100.0% (1/1) Structs : 41.4% (24/58) Typedefs : 35.1% (20/57) Unions : 0.0% (0/1) Variables : 35.2% (205/583) ----------------------------------- Total : 27.3% (817/2988)\n```

**Comment by alessandropellegrini** [comment]
Documentation coverage is 27.3% :exclamation:\[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.\n\n```\nDefines : 15.8% (74/469) Enum Values: 7.5% (63/835) Enums : 25.7% (9/35) Files : 77.1% (81/105) Functions : 40.3% (340/844) Pages : 100.0% (1/1) Structs : 41.4% (24/58) Typedefs : 35.1% (20/57) Unions : 0.0% (0/1) Variables : 35.2% (205/583) ----------------------------------- Total : 27.3% (817/2988)\n```

**Comment by alessandropellegrini** [comment]
Documentation coverage is **27.3%** :exclamation:\n\n[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.\n\n```\nDefines : 15.8% (74/469) Enum Values: 7.5% (63/835) Enums : 25.7% (9/35) Files : 77.1% (81/105) Functions : 40.3% (340/844) Pages : 100.0% (1/1) Structs : 41.4% (24/58) Typedefs : 35.1% (20/57) Unions : 0.0% (0/1) Variables : 35.2% (205/583) ----------------------------------- Total : 27.3% (817/2988)\n```

**Comment by alessandropellegrini** [comment]
Documentation coverage is **27.3%** :exclamation:\n\n[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.\n\n```\nDefines : 15.8% (74/469) Enum Values: 7.5% (63/835) Enums : 25.7% (9/35) Files : 77.1% (81/105) Functions : 40.3% (340/844) Pages : 100.0% (1/1) Structs : 41.4% (24/58) Typedefs : 35.1% (20/57) Unions : 0.0% (0/1) Variables : 35.2% (205/583) ----------------------------------- Total : 27.3% (817/2988)\n```

**Comment by alessandropellegrini** [comment]
Documentation coverage is **27.3%**     :exclamation:\n\n[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.\n\n```\nDefines    :  15.8% (74/469)
Enum Values:   7.5% (63/835)
Enums      :  25.7% (9/35)
Files      :  77.1% (81/105)
Functions  :  40.3% (340/844)
Pages      : 100.0% (1/1)
Structs    :  41.4% (24/58)
Typedefs   :  35.1% (20/57)
Unions     :   0.0% (0/1)
Variables  :  35.2% (205/583)
-----------------------------------
Total      :  27.3% (817/2988)\n```

**Comment by alessandropellegrini** [comment]
Documentation coverage is **%** 
[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage//) is available.

```
A    :  12 %
A    :  12 %
A    :  12 %
A    :  12 %
A    :  12 %
A    :  12 %
------------
rowqirjowqirjwq
```

**Comment by alessandropellegrini** [comment]
Documentation coverage is **27.3%** :exclamation:
[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.

```
Defines    :  15.8% (74/469)
Enum Values:   7.5% (63/835)
Enums      :  25.7% (9/35)
Files      :  77.1% (81/105)
Functions  :  40.3% (340/844)
Pages      : 100.0% (1/1)
Structs    :  41.4% (24/58)
Typedefs   :  35.1% (20/57)
Unions     :   0.0% (0/1)
Variables  :  35.2% (205/583)
-----------------------------------
Total      :  27.3% (817/2988)
```

**Comment by alessandropellegrini** [comment]
Documentation coverage is **27.3%** :exclamation:
[More detailed information](https://hpdcs.github.io/ROOT-Sim/docs/coverage/135/) is available.

```
Defines    :  15.8% (74/469)
Enum Values:   7.5% (63/835)
Enums      :  25.7% (9/35)
Files      :  77.1% (81/105)
Functions  :  40.3% (340/844)
Pages      : 100.0% (1/1)
Structs    :  41.4% (24/58)
Typedefs   :  35.1% (20/57)
Unions     :   0.0% (0/1)
Variables  :  35.2% (205/583)
-----------------------------------
Total      :  27.3% (817/2988)
```

**Review by Piccions — APPROVED** [review]
This stuff seems to work, so I approve it!

**Pull request merged**
