### PR TITLE
Models

### PR DESCRIPTION
**Pull request by readbeard**
This commit introduces:
- MPI messages involving dynamic size structs bugfix
- Removal of unuseful prints
- Introduction of a new version of the _nosql_ model

 **Beware**: the hotfix we introduced in the _models_spoonfix_ branch to overcome the VMWARE communication problem is not included in this PR. Indeed, this problem is not showing when running the same code on another platform (on MNIV it successfully completed)

### CODE REVIEW

**Comment by ael-code** [comment]
This PR should not be merged upstream. It contains a lot of conflicts with the current code in `release-2.0.0` branch. You are proposing the same fixes (almost) that have been merged with #89.

@readbeard I suggest to make a PR with just the code of the new nosql model. Moreover since we are under version control it does not make much sense to me to create a old-nosql model.

**Comment by alessandropellegrini** [comment]
I do agree with avoiding to re-merge changes that are already upstream.

The point is that I want to be 100% sure that there's no difference between #89 and the current `models` branch, due to the edits that were made in the very last days of development.

`old-nosql` could be dropped. The point here is to understand how different are the two models, and whether we need to develop a final new version.

@readbeard could you please take care of this?

If this PR cannot be realigned to the current state of `release-2.0.0`, we should close it.

**Comment by alessandropellegrini** [comment]
Additionally, if possible, squash the commits which are `temp-*` or non-meaningful for version control. Thanks!

**Review by alessandropellegrini — APPROVED** [review]
This is not a completely clean PR.
Anyhow, at this point in the development phase, I consider this mergeable. Indeed, we have issues #15  and #16 still pending. The `ECS` macro should be replaced with a system-wide one, once #15 is addressed. The code should be significantly cleaned up in #16. Additionally, with respect to #105, all ECS code should be cleaned up.
Overall, this boils down to slight changes in the current ECS base in `release-2.0.0` which is still not final, and evolves the `nosql` model.

**Pull request merged**
